name := "combinators"
version := "1.0"
scalaVersion := "2.11.11"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.6"
libraryDependencies += "io.spray" %%  "spray-json" % "1.3.3"